PROJECT_NAME := carbon_default-chan
REVISION := rev3
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-default-chan-carbon
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/default_chan_proj.mk
