PROJECT_NAME := carbon_default-4rx-chan
REVISION := rev4
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-default-chan-carbon
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/default-4rx-chan_proj.mk
